### PR TITLE
fix: use as_chunk instead of as_paragraph when adding chunks

### PR DESCRIPTION
**Pull request by davidgohel**
Hello,

After a code refactoring of 'flextable', we detected that your package uses `as_paragraph()` instead of `as_chunk()` as argument(s) to `append_chunks()`. This needs to be corrected to avoid a problem with the next version of flextable to be sent to CRAN (not for at least two weeks).

This PR fixes the issues.

KR,
David

### CODE REVIEW

**Comment by sfcheung** [comment]
Thanks a lot for spotting the problem, @davidgohel .

I ran some tests locally, on R 4.3.3, flextable 0.9.4. Some of the tests failed. These tests are long tests and so are enabled only for developmental version with version number having the fourth part (e.g., x.x.x.x).

This is an example:

https://github.com/sfcheung/manymome.table/blob/6d729facd1ca6f6f570aa2d3bab043dd582448d6/inst/tinytest/test_indirect_list.R#L107

```r
> tmp1 <- as_flextable(stdx_boot, pvalue = TRUE, pcut = .005, group_by_x = FAL$
Error in formatter(x, ...) : could not find function "formatter"
```

I checked and the error did not occur with `as_paragraph()`.

If I change `as_paragraph()` to `as_chunk()` now and submit to CRAN, it will not work with the current CRAN version of flextable.

Using the current GitHub version of flextable (0.9.5.018), an error occurred on another line:

https://github.com/sfcheung/manymome.table/blob/6d729facd1ca6f6f570aa2d3bab043dd582448d6/inst/tinytest/test_indirect_list.R#L83

```r
> tmp1 <- as_flextable(out_boot,
+                      var_labels = c(x1 = "IV_A",
+                                     x2 = "IV_B",
+                                     y1 = "DV_A",
+                                     y2 = "DV_B"),
+                      se = TRUE,
+                      pvalue = TRUE,
+                      digits = 4)
Error in append_chunkset_struct_element(x = x[[part]]$content, i = i,  : 
  nrow(chunk_data) == expected_length is not TRUE
```

May I know how I can further update manymome.table such that it will work with both the current CRAN version and the upcoming version of flextable?

I though about submitting a version to CRAN that uses `as_paragraph()` or `as_chunk()` conditionally, depending on the version of flextable? However, it seems that the error above cannot be solved this way.

Sorry for the inconvenience caused.

**Comment by davidgohel** [comment]
Thanks, I took a look and I think it is now ok. (I did push another commit)

I am expecting that it is possible to submit with only these `as_chunk()` changes. 

Before you posted your comments, I did not test with a `x.x.x.x` version. Sorry, I should have been more careful.

Let me know if you think there are still issues

**Review by sfcheung — APPROVED** [review]

**Comment by sfcheung** [comment]
Many many thanks for your help! And thanks a lot for developing flextable, which is an excellent package. I am new to it and this is the first time I use it. If there are any other issues that I need to pay attention to when working with flextable, please let me know. I will revise the code accordingly in the future to follow the best practice to use flextable.

**Comment by davidgohel** [comment]
Thank you for merging the PR


> If there are any other issues

Not an issue but a suggestion... When I took a look at your package, I saw some call to `autofit()`. You could maybe (to be tested) increase the `add_w` setting, as I am almost sure I saw some text wrap - to be sure they all are display on a single line:

```
flextable::autofit(ft, add_w = .2)# default to .1
```

**Comment by sfcheung** [comment]
Thanks for the suggestion. I will look into it when the next version of flextable is released.

By the way, the latest version of manymome.table, which should be compatible with the forthcoming version of flextable, is on its way to CRAN.

**Comment by davidgohel** [comment]
great, many thanks. I think I can now send flextable to CRAN

**Pull request merged**
